[package]
name = "heart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const-str = "0.3.1"
colored = "2"
lazy_static = "1.4.0"

